name: Deploy changes to gh-pages

on: [push]

jobs:
  build:
    name: Checkout and deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10]

    steps:
    - uses: actions/checkout@v2
    - run: git config user.name "GitHub Actions"
    - run: git config user.email "actions@users.noreply.github.com"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run deploy
      
#     - run: npm test
#       env:
#         CI: true
